Adjusting Utils for new Model Shape
gladly-team/tab pull request #1034
Opened 2021-08-23 16:29 UTC by jedtan

2021-08-23 19:29 UTC, amaliwanag2 approved these changes

2021-08-23 20:03 UTC, amaliwanag2 requested changes
looks like there's one test failing

2021-08-24 00:48 UTC, amaliwanag2 reviewed
can you update the fixture data as well to have the new mission max tabs day data shape?

2021-08-24 16:27 UTC, jedtan commented
Updated!

2021-08-30 19:58 UTC, merged