Alec/tfac 553
gladly-team/tab pull request #1075
Opened 2021-09-24 17:07 UTC by amaliwanag2

2021-09-24 19:02 UTC, amaliwanag2 commented on graphql/database/videoAdLog/isVideoAdEligible.js
> +  (await VideoAdLogModel.query(userContext, userId)
if a user clicks then immedietely closes a video ad, we don't want it to count

2021-09-27 15:33 UTC, kmjennison requested changes
Small changes, then LGTM and merge away!

2021-09-27 15:33 UTC, kmjennison commented on graphql/database/videoAdLog/__tests__/createVideoAdLog.test.js
> +  it('throws if user id does not match user context false if user has  3 completed video ad logs in the last 24 hours', async () => {
Fix test description

2021-09-27 15:33 UTC, kmjennison commented on graphql/database/videoAdLog/__tests__/isVideoAdEligible.test.js
> +  })
Add a test with >3 items but <3 are completed.

2021-09-27 15:33 UTC, kmjennison commented on graphql/data/schema.js
> +  description: 'Vidieo Ad Log type',
Typo

2021-09-27 15:33 UTC, kmjennison commented on graphql/database/videoAdLog/VideoAdLogModel.js
> +        .description('user has aknowledged that the mission has completed'),
Fix description

2021-09-27 19:05 UTC, merged